vco_address  = "https://vco.velocloud.net/portal/rest/"
vco_url      = "vco.velocloud.net"
vco_username = "vco_user@email.com"
vco_password = "your_password"
edge_profile = "AWS-PROFILE"
cidr_block     = "10.0.0.0/8"
